FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt requirements.txt

RUN apt-get update && \
    apt-get install -y gcc libpq-dev && \
    pip install -r requirements.txt

COPY . .

CMD ["python", "app.py"]
